name: Deploy Migrations to Supabase

on:
  push:
    branches: [ master ]
    paths:
      - 'supabase/migrations/**'
  workflow_dispatch: # 添加手動觸發功能

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Supabase CLI
        uses: supabase/setup-cli@v1
        with:
          version: latest
      
      - name: Deploy migrations
        run: |
          supabase link --project-ref ${{ secrets.SUPABASE_PROJECT_ID }} --password "@Vu4ej388##" --debug
          supabase db push
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
